import { supabase } from './client.ts';
import { fetchAll } from './paging.ts';
import type { Insert, Row } from './types.ts';

export type Medication = Row<'medications'>;
/** The columns a person fills in. `active` is generated by the database from end_date, so it is never written. */
export type MedicationInput = Omit<Insert<'medications'>, 'id' | 'created_at' | 'active'>;

export function fetchMedications(): Promise<Medication[]> {
  return fetchAll<Medication>(
    (from, to) => supabase.from('medications').select('*').order('start_date', { ascending: false, nullsFirst: false }).order('created_at').order('id').range(from, to),
    'medications',
  );
}

export async function saveMedication(id: string | null, input: MedicationInput): Promise<void> {
  const { error } = id === null
    ? await supabase.from('medications').insert(input)
    : await supabase.from('medications').update(input).eq('id', id);
  if (error) throw new Error(error.message);
}

export async function deleteMedication(id: string): Promise<void> {
  const { error } = await supabase.from('medications').delete().eq('id', id);
  if (error) throw new Error(error.message);
}
